"""Added artist and venue fields

Revision ID: bf95da278511
Revises: d3fa960ac166
Create Date: 2020-03-30 17:51:56.961856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf95da278511'
down_revision = 'd3fa960ac166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('site_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('site_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'site_link')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Artist', 'site_link')
    op.drop_column('Artist', 'seeking_venues')
    # ### end Alembic commands ###
